

export const SET_PRODUCTS = "SET_PRODUCTS";

export const ADD_PRODUCT = "ADD_PRODUCT";

export const REMOVE_PRODUCT = "REMOVE_PRODUCT";

export const SET_STORE_PRODUCTS = "SET_STORE_PRODUCTS";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";


export const SET_UPDATE_PRODUCT = 'SET_UPDATE_PRODUCT'
export const CLEARUPDATE = "CLEARUPDATE"